site_url: https://projetos-de-extensao.github.io/PBE_25.2_8001_II/
repo_url: https://github.com/jonh-carvalho/PBE_25.2_8001_II
site_author: Jonh Carvalho
site_name: PBE_25.2_8001_II
copyright: Copyright ©️ 2025, Jonh Carvalho

nav: 
  - Home: index.md
  - Disciplina:
    - Aulas: Disciplina/aulas.md
    - Ambiente: Disciplina/ambiente.md
    - Github: Disciplina/github.md
    - Mkdocs: Disciplina/mkdocs.md
    - CodeSpace: Disciplina/codespace.md
    - Avaliações: Disciplina/avalia.md
    - Dojo:
      - Index: Disciplina/dojo/dojo.md
      - Setup: Disciplina/dojo/setup.md
      - TDD/Pair: Disciplina/dojo/tddpairprogramming.md
    - Roteiros:
      - Iniciação:
        - Design Thinking: Disciplina/Roteiros/Iniciação/04_DesignThinking.md
        - UP: Disciplina/Roteiros/Iniciação/04_UPgithub.md
      - Elaboração:
        - Requisitos: Disciplina/Roteiros/Elaboração/req_biblioteca.md
        - Casos de Uso: Disciplina/Roteiros/Elaboração/uc_biblioteca.md
        - Diagrama de Classes: Disciplina/Roteiros/Elaboração/class_biblioteca.md
      - Construção:
        - Poo:
          - Intro OO: Disciplina/Roteiros/Construção/Poo/Conceitos-basicos-de-OO.pdf
          - Procedural x OO: Disciplina/Roteiros/Construção/Poo/proceduralXpoo.ipynb
          - Intro Python OO: Disciplina/Roteiros/Construção/Poo/poo.ipynb
          - Python OO: Disciplina/Roteiros/Construção/Poo/Python-OO.pdf
        - Django:
          - Intro: Disciplina/Roteiros/Construção/Django/01_Intro.md
          - Intro Rest: Disciplina/Roteiros/Construção/Django/02_Intro Django Rest.md
  
  - Iniciação:
      - Index: Iniciacao/index.md
      - Pesquisa: Iniciacao/pesquisa.md
      - 5w2h: Iniciacao/5w2h.md
      - Design Thinking: Iniciacao/design_thinking.md
      - Brainstorming: Iniciacao/Brainstorm.md      
      - Mapa Mental: Iniciacao/mapa_mental.md
      - Prototipagem Baixa Fidelidade: Iniciacao/prototipo_baixa_fidelidade.md
  - Elaboração:
      - Index: Elaboracao/index.md
      - Requisitos: Elaboracao/dsc.md                 
      - Casos de Uso: Elaboracao/casos_de_uso.md
      - Diagrama de Classes: Elaboracao/diagrama_de_classes.md
      - Diagrama de Sequência: Elaboracao/diagrama_de_sequencia.md
      - Protótipo de Alta Fidelidade: Elaboracao/prototipo_alta_fidelidade.md
  - Construção:
      - Index: Construcao/index.md
      - Git Issues: Construcao/git_issues.md
      - GitHub Projects: Construcao/github_project.md  
      - CodeSpace: Construcao/codespace.md             
  - Transição:
      - Index: Transicao/index.md
  - Site:
      - Link: https://monitoria-conecta.lovable.app/auth/login


extra_css:
  - css/extra.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true

plugins:
  - minify:
      minify_html: true
  - search

theme:
  name: material
  logo: assets/ibmec_logo.png    
  language: pt-BR
  favicon: images/favicon.png     
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: black
      toggle:
        icon: material/toggle-switch-off
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      accent: amber
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
      color_mode: dark
  user_color_mode_toggle: true

  features:
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    logo: simple/react
    favicon: simple/react
