# Generated by Django 5.2.7 on 2025-10-17 14:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('aluno', 'Aluno'), ('monitor', 'Monitor'), ('professor', 'Professor'), ('coordenador', 'Coordenador')], default='aluno', max_length=20)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField(blank=True, null=True)),
                ('vagas', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_limite', models.DateField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta para Candidaturas'), ('fechada', 'Fechada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('coordenador', models.ForeignKey(limit_choices_to={'tipo_usuario': 'coordenador'}, on_delete=django.db.models.deletion.CASCADE, related_name='monitorias_criadas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('reprovada', 'Reprovada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('observacoes_aluno', models.TextField(blank=True, null=True)),
                ('observacoes_coordenador', models.TextField(blank=True, null=True)),
                ('aluno', models.ForeignKey(limit_choices_to={'tipo_usuario': 'aluno'}, on_delete=django.db.models.deletion.CASCADE, related_name='minhas_candidaturas', to=settings.AUTH_USER_MODEL)),
                ('monitoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='myapp.monitoria')),
            ],
            options={
                'unique_together': {('aluno', 'monitoria')},
            },
        ),
        migrations.CreateModel(
            name='MonitoriaAtiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('candidatura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoria_ativa', to='myapp.candidatura')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioMonitoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('local', models.CharField(default='Laboratório de Informática', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('monitoria_ativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='myapp.monitoriaativa')),
            ],
        ),
    ]
